# Generated by Django 5.0.3 on 2024-05-26 20:52

import librarian.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0002_returnlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnlog',
            name='expiryLogTime',
            field=models.DateTimeField(default=librarian.models.book_returnlog_expiry),
        ),
    ]
