# Generated by Django 5.0.3 on 2024-05-26 21:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0003_returnlog_expirylogtime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='borrowed',
            field=models.ManyToManyField(blank=True, related_name='borrow', to=settings.AUTH_USER_MODEL),
        ),
    ]
