# Generated by Django 5.0.3 on 2024-05-26 22:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0004_alter_books_borrowed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='borrowed',
            field=models.ManyToManyField(blank='True', related_name='borrow', to=settings.AUTH_USER_MODEL),
        ),
    ]
