# Generated by Django 5.0.3 on 2024-09-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0006_subsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsection',
            name='sub_category',
            field=models.CharField(default='Def', max_length=100),
        ),
    ]
