# Generated by Django 5.0.3 on 2024-09-01 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0007_alter_subsection_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsection',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.subcategory'),
        ),
    ]
