# Generated by Django 5.0.3 on 2024-09-03 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0008_alter_subsection_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='books',
            name='SubCategory',
        ),
        migrations.AddField(
            model_name='books',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='librarian.category'),
        ),
        migrations.AddField(
            model_name='books',
            name='SubCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='librarian.subcategory'),
        ),
    ]
