# Generated by Django 5.0.3 on 2024-09-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0009_remove_books_category_remove_books_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='books',
            name='SubCategory',
        ),
        migrations.AddField(
            model_name='books',
            name='Category',
            field=models.ManyToManyField(null=True, to='librarian.category'),
        ),
        migrations.AddField(
            model_name='books',
            name='SubCategory',
            field=models.ManyToManyField(to='librarian.subcategory'),
        ),
    ]
