# Generated by Django 5.0.3 on 2024-09-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0010_remove_books_category_remove_books_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='SubSection',
            field=models.ManyToManyField(to='librarian.subsection'),
        ),
    ]
