# Generated by Django 5.0.3 on 2024-09-23 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0011_books_subsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='BookTitle',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='books',
            name='Category',
        ),
        migrations.AddField(
            model_name='books',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='librarian.category'),
        ),
    ]
