# Generated by Django 5.0.3 on 2024-09-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0012_alter_books_booktitle_remove_books_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='Category',
        ),
        migrations.AddField(
            model_name='books',
            name='Category',
            field=models.ManyToManyField(null=True, to='librarian.category'),
        ),
    ]
