# Generated by Django 5.0.3 on 2024-09-25 06:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0013_remove_books_category_books_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Category',
            field=models.ManyToManyField(to='librarian.category'),
        ),
        migrations.AddIndex(
            model_name='approvedrequest',
            index=models.Index(fields=['book', 'requested_by'], name='librarian_a_book_id_25aa7b_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrequest',
            index=models.Index(fields=['book', 'requested_by'], name='librarian_b_book_id_833bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='declinedrequest',
            index=models.Index(fields=['book', 'requested_by'], name='librarian_d_book_id_0fdb5d_idx'),
        ),
    ]
