# Generated by Django 5.0.3 on 2024-09-29 18:39

import django.db.models.deletion
import librarian.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0016_alter_out_requested_by_alter_returnlog_requested_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='out',
            name='requested_by',
            field=models.ForeignKey(default=librarian.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='requested_by',
            field=models.ForeignKey(default=librarian.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
