# Generated by Django 5.0.3 on 2024-10-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0017_alter_out_requested_by_alter_returnlog_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='declinedrequest',
            name='decline_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
