# Generated by Django 5.0.3 on 2024-10-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0018_declinedrequest_decline_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declinedrequest',
            old_name='decline_reason',
            new_name='reason',
        ),
    ]
