# Generated by Django 5.0.3 on 2024-10-02 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0019_rename_decline_reason_declinedrequest_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declinedrequest',
            old_name='reason',
            new_name='decline_reason',
        ),
    ]
