# Generated by Django 5.0.3 on 2024-10-29 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0020_rename_reason_declinedrequest_decline_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsection',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='librarian.subcategory'),
        ),
    ]
