# Generated by Django 5.0.3 on 2024-11-04 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0022_alter_subcategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvedrequest',
            old_name='expireTime',
            new_name='expires_at',
        ),
    ]
