# Generated by Django 5.0.3 on 2025-01-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0023_rename_expiretime_approvedrequest_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='ISBN',
            field=models.CharField(default='Def', max_length=100),
        ),
    ]
