# Generated by Django 5.0.3 on 2024-10-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_notification_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('approved', 'Approved'), ('declined', 'Declined')], max_length=50, null=True),
        ),
    ]
