# Generated by Django 5.0.3 on 2024-10-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('approved', 'Approved'), ('declined', 'Declined'), ('expired', 'Expired')], max_length=50),
        ),
    ]
