# Generated by Django 5.0.3 on 2024-12-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('approved', 'Approved'), ('declined', 'Declined'), ('expired', 'Expired'), ('reminder', 'Reminder')], max_length=50),
        ),
    ]
