# Generated by Django 5.0.3 on 2024-05-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrn', models.CharField(max_length=12)),
                ('fname', models.CharField(max_length=50, verbose_name='First Name')),
                ('lname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('address', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('fname', models.CharField(default='', max_length=50, verbose_name='First Name')),
                ('lname', models.CharField(default='', max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(default='', max_length=50, verbose_name='Email')),
                ('Bday', models.DateField()),
            ],
        ),
    ]
