# Generated by Django 5.0.3 on 2024-08-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='lrn',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
