# Generated by Django 5.0.3 on 2024-12-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_remove_account_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrn', models.CharField(max_length=12, unique=True, verbose_name='LRN')),
                ('fname', models.CharField(max_length=50, verbose_name='First Name')),
                ('lname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
            ],
        ),
    ]
